# For configuration options and examples, please see:
# https://github.com/benphelps/homepage/wiki/Bookmarks

- Developer:
    - Github:
        - abbr: GH
          href: https://github.com/
    - Vercel:
        - abbr: VC
          href: https://vercel.com/dashboard

- Extenal tools:
    - Dynamic DNS:
        - abbr: DNS
          href: https://www.dynu.com/en-US/ControlPanel
    - Duck DNS:
        - abbr: DNS
          href: https://www.duckdns.org/

- Online storage:
    - Google drive:
        - abbr: GD
          href: https://drive.google.com/drive/u/0/my-drive
